server:
  port: 8083
spring:
  application:
    name: risk-service
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: 27017
      database: risk_db
      username: ${MONGO_USER:root}
      password: ${MONGO_PASSWORD:example}
      authentication-database: admin
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: risk-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.paymentservice.dto.request, com.example.riskservice.dto"
      auto-offset-reset: earliest
    topic:
      check-required: risk-check-required
      check-approved: risk-check-approved


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka