server:
  port: 8080
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: account-service
#              uri: http://localhost:8081
              uri: lb://account-service
              predicates:
                - Path=/accounts/**
            - id: payment-service
#              uri: http://localhost:8082
              uri: lb://payment-service
              predicates:
                - Path=/payments/**
            - id: risk-service
#              uri: http://localhost:8083
              uri: lb://risk-service
              predicates:
                - Path=/risks/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: account-service
        url: /account-service/v3/api-docs
      - name: payment-service
        url: /payment-service/v3/api-docs
      - name: risk-service
        url: /risk-service/v3/api-docs
  api-docs:
    path: /v3/api-docs


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



