server:
  port: 8082
spring:
  application:
    name: payment-service
  data:
    mongodb:
#      uri:  mongodb://root:example@localhost:27017/payment_db
      host: ${MONGO_HOST:localhost}
      port: 27017
      database: payment_db
#      uri: mongodb://localhost:27017/payment_db
      username: ${MONGO_USER:root}
      password: ${MONGO_PASSWORD:example}
      authentication-database: admin
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      auto-offset-reset: earliest



account:
  service:
    url: http://localhost:8081

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
